### ISSUE TITLE
User guide for Scrapydweb | Q&A | 用户指南 | 常见问题

### ISSUE THREAD

**Issue by LWsmile** [my8100/scrapydweb#7]
linux：HTTPConnectionPool(host='192.168.0.24', port=6801): Max retries exceeded with url: /listprojects.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0a78b2d828>: Failed to establish a new connection: [Errno 111] Connection refused',))
windows：HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jobs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000004589CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
这个我应该怎么解决呢？

**Comment by my8100** [comment]
Make sure that [Scrapyd ](https://github.com/scrapy/scrapyd) has been installed and started.
Then visit the Scrapyd server (in your case: [http://192.168.0.24:6801](http://192.168.0.24:6801))  to check the connectivity.

**Comment by my8100** [comment]
> 配置文件我应该怎么配置呢？能不能发生产环境一个模板呢？

FYI

[How to efficiently manage your distributed web scraping projects](https://medium.com/@my8100/https-medium-com-my8100-how-to-efficiently-manage-your-distributed-web-scraping-projects-55ab13309820)

[如何简单高效地部署和监控分布式爬虫项目](https://juejin.im/post/5bebc5fd6fb9a04a053f3a0e)

**Comment by my8100** [comment]
**Leave your comment here for help, in English if possible.**
**使用过程中如有疑问，请添加评论，尽量用英语。**

**Comment by zhangshengchun** [comment]
CPU occupancy is too high when  i refresh the statistical information，and the web interface has been waiting for a long time. i using scrapyweb to manage 25 scrapyd server nodes，how can I solve it?

**Comment by zhangshengchun** [comment]
@my8100 The problem of high CPU usage has been solved. thanks a lot!

**Comment by my8100** [comment]
@zhangshengchun You have to manually restart the Scrapyd service. (Note that this operation would **reset the running jobs at the same time** since it keeps all job data in memory. ) That's why ScrapydWeb displays the finished jobs in the descending order.

**Comment by KimFu2** [comment]
did you hava a docker deploy version?

**Comment by my8100** [comment]
Why not try it yourself and share with us?

**Comment by KimFu2** [comment]
> Why not try it yourself and share with us?

ok.If there is, I don't have to do it. If not, I will do it and share it.

**Comment by my8100** [comment]
FYI
```
$ cat docker-entrypoint.sh 
#!/bin/bash
mkdir /code/logs
/usr/bin/nohup /usr/local/bin/logparser -t 10 -dir /code/logs > logparser.log 2>&1 &
#TO KEEP THE CONTAINER RUNNING
/usr/local/bin/scrapyd  > scrapyd.log
```

**Comment by 1034467757** [comment]
Hello,I have some questions.How can I start more than one spider in a single scrapyd server without using timer task?In my project,I need to start lots of spiders at the same time(like batch start),or,I need to stop spiders at one scrapyd server.Thanks for your reply !

**Comment by my8100** [comment]
It's not supported yet as I don't think it's a common practice. You can use the Requests library in a Python script instead.

**Comment by 1034467757** [comment]
> It's not supported yet as I don't think it's a common practice. You can use the Requests library in a Python script instead.

OK,thanks!

**Comment by KimFu2** [comment]
Is SCRAPYDWEB a true distributed crawler?Use the same queue like Scrapy-redis, or the crawler is running independently?

**Comment by my8100** [comment]
ScrapydWeb is a web application for Scrapyd cluster management, not a crawler. Have you read the readme and these [tutorials](https://github.com/my8100/files)?

**Comment by fishmisswater** [comment]
How to  set up the SCRAPYD_LOGS_DIR option? I try this:
![image](https://user-images.githubusercontent.com/11415507/55929382-f9395780-5c4e-11e9-9f5d-2523d999e476.png)
![image](https://user-images.githubusercontent.com/11415507/55929402-0e15eb00-5c4f-11e9-950b-f91b8c4ba520.png)
![image](https://user-images.githubusercontent.com/11415507/55929416-1ec66100-5c4f-11e9-95a9-888335ab32e1.png)
and this:
![image](https://user-images.githubusercontent.com/11415507/55929609-10c51000-5c50-11e9-91fa-91abe0159e8f.png)
![image](https://user-images.githubusercontent.com/11415507/55929637-2afeee00-5c50-11e9-925e-e9019624c9a3.png)
neither work

**Comment by my8100** [comment]
```
# Check out this link to find out where the Scrapy logs are stored:
# https://scrapyd.readthedocs.io/en/stable/config.html#logs-dir
# e.g. 'C:/Users/username/logs/' or '/home/username/logs/'**
SCRAPYD_LOGS_DIR = ''
```

**Comment by fishmisswater** [comment]
thx ! but I still don't konw how to fix it:
the scrapyd.conf file shows my scrapyd log dir is"/root/logs" :
![image](https://user-images.githubusercontent.com/11415507/55930337-58996680-5c53-11e9-902b-3b9980532fe4.png)
![image](https://user-images.githubusercontent.com/11415507/55930375-7cf54300-5c53-11e9-9e2e-2904ec7f1787.png)
![image](https://user-images.githubusercontent.com/11415507/55930437-bfb71b00-5c53-11e9-8223-2dbf35e3bf53.png)

**Comment by my8100** [comment]
There's no need to config the `SCRAPYD_LOGS_DIR` option if you are not running any Scrapyd server on the ScrapydWeb host.

**Comment by fishmisswater** [comment]
aha, it's running on the server side.

**Comment by sun8029554** [comment]
Hello，I feel better if u can add time filtering to the task page.

**Comment by my8100** [comment]
> Hello，I feel better if u can add time filtering to the task page.

@sun8029554 Could you explain the need of  "time filtering" in detail?

**Comment by jiuheit** [comment]
`{"node_name": "WIN-HPEPRHCCLL4", "status", "error", "message": "Expected one of [b'HEAD', b'object', b'POST']}`
The crawler that integrates selenium cannot stop. How can this problem be solved?

**Comment by my8100** [comment]
How did you get that response? Any more logs?

**Comment by jiuheit** [comment]
> How did you get that response? Any more logs?

Other reptiles that do not integrate selenium can stop normally
![sns443526445](https://user-images.githubusercontent.com/41412950/56469979-2833a280-6473-11e9-97f3-4827b5df52a8.png)
![TTT](https://user-images.githubusercontent.com/41412950/56469981-2c5fc000-6473-11e9-8cfe-63b3ba1fbafb.png)

**Comment by jiuheit** [comment]
> How did you get that response? Any more logs?

[https://www.cnblogs.com/my8100/p/scrapyd_2_add_stop_start.html](url)
I see that your blog has solutions, but does it seem that there are places in scrapydweb where similar problems have been overlooked?

**Comment by my8100** [comment]
Run scrapydweb with argument "-v", retry and post the related logs here.

**Comment by jiuheit** [comment]
> Run scrapydweb with argument "-v", retry and post the related logs here.

Server side
![scrapydweb-v](https://user-images.githubusercontent.com/41412950/56470078-988ef380-6474-11e9-97e2-f53acbc36fbc.png)

Remote Client Log
[log.log](https://github.com/my8100/scrapydweb/files/3101190/log.log)

**Comment by my8100** [comment]
I need the log of scrapydweb when you click the Stop button.

**Comment by jiuheit** [comment]
> I need the log of scrapydweb when you click the Stop button.

[stop.log](https://github.com/my8100/scrapydweb/files/3101201/stop.log)
Click the log output after stopping

**Comment by jiuheit** [comment]
> I need the log of scrapydweb when you click the Stop button.

![scrapydweb-v](https://user-images.githubusercontent.com/41412950/56470320-5f0bb780-6477-11e9-9012-cb02b3d9156b.png)
I tried to stop using Cmder, and there was an error.

**Comment by jiuheit** [comment]
> I need the log of scrapydweb when you click the Stop button.

I tried to stop using Cmder, and there was an error.
![cmders](https://user-images.githubusercontent.com/41412950/56470334-8f535600-6477-11e9-9aba-ff243fd909cc.png)

**Comment by my8100** [comment]
> > I need the log of scrapydweb when you click the Stop button.
> 
> [stop.log](https://github.com/my8100/scrapydweb/files/3101201/stop.log)
> Click the log output after stopping

You are not running scrapydweb with argument '-v' to change the logging level to DEBUG, please try again and post the logs.

**Comment by my8100** [comment]
> > I need the log of scrapydweb when you click the Stop button.
> 
> I tried to stop using Cmder, and there was an error.
> ![cmders](https://user-images.githubusercontent.com/41412950/56470334-8f535600-6477-11e9-9aba-ff243fd909cc.png)

It seems that Scrapyd got redundant single quotes for the project name.
Try to post the request with the requests library instead.

**Comment by jiuheit** [comment]
> > > I need the log of scrapydweb when you click the Stop button.
> > 
> > 
> > [stop.log](https://github.com/my8100/scrapydweb/files/3101201/stop.log)
> > Click the log output after stopping
> 
> You are not running scrapydweb with argument `-v` or `--verbose` to change the logging level to DEBUG, please try again and post the logs.

Is this log file?
[DEBUGscrapydweb.log](https://github.com/my8100/scrapydweb/files/3101250/DEBUGscrapydweb.log)

**Comment by jiuheit** [comment]
> > > I need the log of scrapydweb when you click the Stop button.
> > 
> > 
> > [stop.log](https://github.com/my8100/scrapydweb/files/3101201/stop.log)
> > Click the log output after stopping
> 
> You are not running scrapydweb with argument `-v` or `--verbose` to change the logging level to DEBUG, please try again and post the logs.

Is this log file?
[DEBUGscrapydweb.log](https://github.com/my8100/scrapydweb/files/3101252/DEBUGscrapydweb.log)

**Comment by my8100** [comment]
Scrapyd only returned `"message": ""`, which helps nothing.
It's not an issue of ScrapydWeb.

Visit the web UI of Scrapyd to make sure that the job is running and under control.
Also, check out the logs of Scrapyd.
```
[2019-04-21 21:57:04,870] DEBUG    in ApiView: POST data: {
    "job": "2019-04-21T10_02_38",
    "project": "2019_4_20_005650"
}
[2019-04-21 21:57:04,909] ERROR    in ApiView: !!!!! (200) error: http://yj.xxxx.com:80/cancel.json
[2019-04-21 21:57:04,909] DEBUG    in ApiView: Got json from http://yj.xxxx.com:80/cancel.json: {
    "auth": [
        "username",
        "password"
    ],
    "message": "",
    "node_name": "WIN-HPEPRHCCLL4",
    "status": "error",
    "status_code": 200,
    "url": "http://yj.xxxx.com:80/cancel.json",
    "when": "2019-04-21 21:57:04"
}
```

**Comment by jiuheit** [comment]
> Scrapyd only returned `"message": ""`, which helps nothing.
> It's not an issue of ScrapydWeb.
> 
> Visit the web UI of Scrapyd to make sure that the job is still running and under control.
> Also, check out the logs of Scrapyd.
> 
> ```
> [2019-04-21 21:57:04,870] DEBUG    in ApiView: POST data: {
>     "job": "2019-04-21T10_02_38",
>     "project": "2019_4_20_005650"
> }
> [2019-04-21 21:57:04,909] ERROR    in ApiView: !!!!! (200) error: http://yj.xxxx.com:80/cancel.json
> [2019-04-21 21:57:04,909] DEBUG    in ApiView: Got json from http://yj.xxxx.com:80/cancel.json: {
>     "auth": [
>         "username",
>         "password"
>     ],
>     "message": "",
>     "node_name": "WIN-HPEPRHCCLL4",
>     "status": "error",
>     "status_code": 200,
>     "url": "http://yj.xxxx.com:80/cancel.json",
>     "when": "2019-04-21 21:57:04"
> }
> ```

Okay. Thank you for continuing to find out why.

**Comment by sun8029554** [comment]
> > Hello，I feel better if u can add time filtering to the task page.
> 
> @sun8029554 Could you explain the need for "time filtering" in detail?

Query the crawler's operation according to the time period, such as querying a week of crawlers, or a few days 。。。I  think it's a common practice for most of the people 。

**Comment by my8100** [comment]
@sun8029554 You mean display all task results within a period of time, like today or this week?

**Comment by my8100** [comment]
> > Why not try it yourself and share with us?
> 
> ok.If there is, I don't have to do it. If not, I will do it and share it.

@KimFu2, [scrapydwebDockerFile](https://github.com/AoeSyL/scrapydwebDockerFile) from @AoeSyL, not verified.

**Comment by ServletJunior** [comment]
我删除了任务 ，还是照样运行，请问怎样暂停或停止，

**Comment by my8100** [comment]
> 我删除了任务 ，还是照样运行，请问怎样暂停或停止，

Replied in #51.

**Comment by Syucryingstar** [comment]
How to solve：bash: scrapydweb: command not found? I use pip3 to install scrapydweb whit no report    @@@error.Thanks.

**Comment by Syucryingstar** [comment]
How to solve：bash: scrapydweb: command not found? I use pip3 to install scrapydweb whit no report error.Thanks.

**Comment by my8100** [comment]
1. `pip3 uninstall scrapydweb`
2. `pip3 install scrapydweb`
3. `scrapydweb`
4. Post all the log if still fail to start scrapydweb.

**Comment by Syucryingstar** [comment]
> 1. `pip3 uninstall scrapydweb`
> 2. `pip3 install scrapydweb`
> 3. `scrapydweb`
> 4. Post all the log if still fail to start scrapydweb.

[root@localhost scrapydweb]# pip3 install scrapydweb
Collecting scrapydweb
  Using cached https://files.pythonhosted.org/packages/71/69/e60d374d7571a55058176bc0df1ce8bc15a9fe113ecba4c49d7e42eac478/scrapydweb-1.2.0-py3-none-any.whl
Requirement already satisfied: logparser==0.8.1 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (0.8.1)
Requirement already satisfied: six>=1.12.0 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (1.12.0)
Requirement already satisfied: requests>=2.21.0 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (2.22.0)
Requirement already satisfied: SQLAlchemy>=1.2.15 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (1.3.4)
Requirement already satisfied: Flask-SQLAlchemy>=2.3.2 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (2.4.0)
Requirement already satisfied: flask>=1.0.2 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (1.0.3)
Requirement already satisfied: setuptools>=40.6.3 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (41.0.1)
Requirement already satisfied: flask-compress>=1.4.0 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (1.4.0)
Requirement already satisfied: APScheduler>=3.5.3 in /usr/local/python/lib/python3.6/site-packages (from scrapydweb) (3.6.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/python/lib/python3.6/site-packages (from requests>=2.21.0->scrapydweb) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/python/lib/python3.6/site-packages (from requests>=2.21.0->scrapydweb) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/python/lib/python3.6/site-packages (from requests>=2.21.0->scrapydweb) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/python/lib/python3.6/site-packages (from requests>=2.21.0->scrapydweb) (2.8)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/python/lib/python3.6/site-packages (from flask>=1.0.2->scrapydweb) (2.10.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/python/lib/python3.6/site-packages (from flask>=1.0.2->scrapydweb) (0.24)
Requirement already satisfied: click>=5.1 in /usr/local/python/lib/python3.6/site-packages (from flask>=1.0.2->scrapydweb) (6.7)
Requirement already satisfied: Werkzeug>=0.14 in /usr/local/python/lib/python3.6/site-packages (from flask>=1.0.2->scrapydweb) (0.15.4)
Requirement already satisfied: tzlocal>=1.2 in /usr/local/python/lib/python3.6/site-packages (from APScheduler>=3.5.3->scrapydweb) (1.3)
Requirement already satisfied: pytz in /usr/local/python/lib/python3.6/site-packages (from APScheduler>=3.5.3->scrapydweb) (2017.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/python/lib/python3.6/site-packages (from Jinja2>=2.10->flask>=1.0.2->scrapydweb) (1.0)
Installing collected packages: scrapydweb
Successfully installed scrapydweb-1.2.0
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@localhost scrapydweb]# scrapydweb
bash: scrapydweb: command not found...

It still doesn't work....

**Comment by my8100** [comment]
Try use non-root user, or use virtualenv.

**Comment by Syucryingstar** [comment]
> Try non-root user, or use virtualenv.

Thanks a lot. ^_^

**Comment by JQ-K** [comment]
求问，定时任务是不是用的0时区时间，比如我定时任务是8点启动，但是实际上显示0点就启动了

**Comment by my8100** [comment]
@JQ-K
Please new an issue with details (logs and screenshots).

**Comment by 1-eness** [comment]
请问可以通过接口或者API来设置定时任务和查询定时任务的状态嘛？现在只能通过网页操作

**Comment by my8100** [comment]
@1-eness 
It may be supported in a future release, via RESTful API.
Is it necessary to add a timer task via API?
What kind of information of a timer task would you like to get from the API?

**Comment by 1-eness** [comment]
> @1-eness
> It may be supported in a future release, via RESTful API.
> Is it necessary to add a timer task via API?
> What kind of information of a timer task would you like to get from the API?

希望可以支持定时任务的CRUD,目前完全只能通过网页，对代码整合有点不友好

**Comment by L2016J** [comment]
请问, 能支持千级数量的定时任务么?

**Comment by my8100** [comment]
@L2016J
Thousands of what? tasks or nodes?

**Comment by L2016J** [comment]
> @L2016J
> Thousands of what? tasks or nodes?

spider tasks

**Comment by my8100** [comment]
I would suggest you **set up the jitter option** to add a random component to the execution time,
since SQLite is used in the background.

![image](https://user-images.githubusercontent.com/37427675/62200133-623c0b00-b3b7-11e9-8e8d-572477456f26.png)

**Comment by kachacha** [comment]
> I would suggest you **set up the jitter option** to add a random component to the execution time,
> as SQLite is being used in the background.
> 
> ![image](https://user-images.githubusercontent.com/37427675/62200133-623c0b00-b3b7-11e9-8e8d-572477456f26.png)

Set it up to perform custom tasks randomly?

**Comment by my8100** [comment]
Execute a task by random delay of [-N, +N] secs, defaults to 0. ([docs](https://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html#module-apscheduler.triggers.cron))

**Comment by kachacha** [comment]
> .（[docs](https://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html#module-apscheduler.triggers.cron)）

Thank you ，I‘ll try it。

**Comment by kachacha** [comment]
my `ENABLE_CACHE ` have not port ,is error "None of your SCRAPYD_SERVERS could be connected.";Thank you for your reply.

**Comment by my8100** [comment]
@kachacha
What do you mean?

**Comment by kachacha** [comment]
Fail to decode json from http://scrapyd********.local:80/logs/stats.json: Expecting value: line 2 column 1 (char 1)

**Comment by kachacha** [comment]
> @kachacha
> What do you mean? Can you post the full log?

This problem has been solved. It's the port problem.

**Comment by my8100** [comment]
> Fail to decode json from http://scrapyd********.local:80/logs/stats.json: Expecting value: line 2 column 1 (char 1)

Post the full log and the content of stats.json.
Or rename *stats.json* to *stats.json.bak* and restart logparser.

**Comment by kachacha** [comment]
'pip install logparser' on host 'scrapyd1.****.local:80' and run command 'logparser' to show crawled_pages and scraped_items.

**Comment by kachacha** [comment]
![image](https://user-images.githubusercontent.com/32049074/62443309-232e0100-b78d-11e9-8a3c-c35d0ba4af08.png)

**Comment by L2016J** [comment]
I am running the service with docker. 
For the **persistence** of timed tasks, (the scheduled task still exists when restarting)
I have mounted in the "/scrapydweb/data" directory, but it has no effect.
What should I do? Thank you

**Comment by my8100** [comment]
Check out the .db files in the data path on your localhost to confirm that it’s mounted successfully. 
Besides, ScrapydWeb v1.3.0 support MySQL and PostgreSQL backend, simply set up the DATABASE_URL option.

**Comment by yutiya** [comment]
```
[2019-08-30 10:35:00,050] INFO     in apscheduler.scheduler: Scheduler started
[2019-08-30 10:35:00,061] INFO     in scrapydweb.run: ScrapydWeb version: 1.4.0
[2019-08-30 10:35:00,062] INFO     in scrapydweb.run: Use 'scrapydweb -h' to get help
[2019-08-30 10:35:00,062] INFO     in scrapydweb.run: Main pid: 5854
[2019-08-30 10:35:00,062] DEBUG    in scrapydweb.run: Loading default settings from /Library/Python/2.7/site-packages/scrapydweb/default_settings.py
Traceback (most recent call last):
  File "/usr/local/bin/scrapydweb", line 11, in <module>
    load_entry_point('scrapydweb==1.4.0', 'console_scripts', 'scrapydweb')()
  File "/Library/Python/2.7/site-packages/scrapydweb/run.py", line 37, in main
    load_custom_settings(app.config)
  File "/Library/Python/2.7/site-packages/scrapydweb/run.py", line 124, in load_custom_settings
    print(u"{star}Overriding custom settings from {path}{star}".format(star=STAR, path=handle_slash(path)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 21: ordinal not in range(128)
```
你好，想知道是哪里出错的呢？谢谢

**Comment by my8100** [comment]
Go to the user home directory (e.g. /home/yourusername ) and try again.

**Comment by yutiya** [comment]
谢谢。我用的python2.7。删除run.py 124行print(u"xxx") 这行改成print("xxx") 就可以运行了。很感谢

**Comment by nam03021vn12** [comment]
Thank for your hard work and sorry for my bad English but i have a question. I have a trouble when deploy scrapyd and scrapydweb to heroku because of dyno restart and all uploaded spiders , logs and timer tasks has deleted. Is there anyway to work around this problem like your demo sever, it seem doesn't have this problem. Thanks.

**Comment by foreverbeyoung** [comment]
When I installed scrapyweb, there is  an error, the error is as follows, how can I solve it?

Collecting pexpect>=4.7.0 (from logparser==0.8.2->scrapydWeb)
  Downloading https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 255kB/s 
Requirement already satisfied: MarkupSafe>=0.23 in ./.local/lib/python3.6/site-packages (from Jinja2>=2.10->flask>=1.0.2->scrapydWeb) (1.1.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect>=4.7.0->logparser==0.8.2->scrapydWeb) (0.6.0)
Installing collected packages: pexpect, logparser, scrapydWeb
  Found existing installation: pexpect 4.2.1
ERROR: Cannot uninstall 'pexpect'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by my8100** [comment]
@foreverbeyoung
Try to install scrapydweb in virtualenv.

**Comment by panithan-b** [comment]
Hello, I am able to set scrapy and scrapydweb and get them running as a separate docker containers, but the pages and items are N/A, not a number as shown in your example at http://scrapydweb.herokuapp.com

The crawlers can be run properly without any errors shown.
Here are what I have tried:
1. In scrapyd.conf, I set `items_dir=/spider/items`
2. In scrapydweb_settings_v10.py, I set `SHOW_SCRAPYD_ITEMS = True`
3. When run, I expected some items from customspider in /spider/items, but actually there is no file there

![Screen Shot 2562-09-25 at 14 41 25](https://user-images.githubusercontent.com/7359710/65580849-a2c59880-dfa4-11e9-9cc0-66aefed8aa50.png)

**Comment by my8100** [comment]
@panithan-b
Run scrapyd, scrapydweb, and logparser outside dockers to figure out how they cooperate first,
then update your dockers accordingly.

**Comment by panithan-b** [comment]
Hello, I've tried running scrapyd, scrapydweb, and logparser outside docker and got a log file like this, still not sure why most fields are still "N/A" or null
https://pastebin.com/WqRZYcAB

**Comment by my8100** [comment]
What’s the content in file “/spider/logs/tzspider/cosmenet/7dc32862e10311e9bb640242ac130002.log"

**Comment by panithan-b** [comment]
It was the blank file. But now I just know what happened. I set the LOG_LEVEL to ERROR in the scrapy config file for staging environment so it won't print anything except the ERROR level when it runs properly.

Now I set it to INFO and finally able to see the log content, the number of page crawled, and scraped items. :)

**Comment by Ray916** [comment]
Hello，how to make the send_text work, I want to use email to alert, but I dont understand what the code in the send_text page do, thank you

**Comment by stone0311** [comment]
hi, When I run the ninth crawler on each server, it shows waiting to run. How do I set it up to increase the number of crawlers that each server runs?looking forward to your answer.

**Comment by kachacha** [comment]
> hi, When I run the ninth crawler on each server, it shows waiting to run. How do I set it up to increase the number of crawlers that each server runs?looking forward to your answer.

Set in the config of scrapyd. [...\scrapyd\default_scrapyd.conf](https://scrapyd.readthedocs.io/en/stable/config.html#example-configuration-file)

**Comment by stone0311** [comment]
> > 嗨，当我在每台服务器上运行第九个搜寻器时，它显示等待运行。我该如何设置它以增加每个服务器运行的搜寻器的数量？期待您的回答。
> 
> 在scrapyd的配置中设置。[... \ scrapyd \ default_scrapyd.conf](https://scrapyd.readthedocs.io/en/stable/config.html#example-configuration-file)

thank you

**Comment by zaifei5** [comment]
Why does my timer always run twice?

**Comment by icella** [comment]
How display real ip in "servers" view page - [scrapyd servers],  not '127.0.0.1:6800'?

Now i configured scrapyd_servers in a tuple like ('username', 'password', '127.0.0.1', '6801', 'group'), and the web page dispaly '127.0.0.1:6800', but i wanto real ip , so how to configure SCRAPYD_SERVERS. help pls~~~
![20201022114154](https://user-images.githubusercontent.com/3202062/96822031-b408ff00-145b-11eb-8ff0-b941fd48ef81.jpg)

**Comment by PandyYang** [comment]
为啥我的机器启动报错了，AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by PShiYou** [comment]
Hello, can I record a full scrapydweb tutorial video? I followed the tutorials on the Internet and reported all kinds of mistakes

**Comment by PShiYou** [comment]
Hello, can you record a full scrapydweb tutorial video? I followed the tutorials on the Internet and reported all kinds of mistakes

**Comment by dataknower** [comment]
董圣源已经收到您的来信~会尽快回复 谢谢This is Bruce Dong . I have received your letter and will answer you as soon as possible,Thanks.

**Comment by 488443059** [comment]
I got some errors but I installed the modules
![屏幕截图 2024-02-01 133800](https://github.com/my8100/scrapydweb/assets/130025546/22eccac6-c0e4-48cd-a160-bd0ec27a1243)

**Comment by 488443059** [comment]
An error occurred while uploading the project str object has no attribute decode

**Comment by Aaron2516** [comment]
Some of my existing projects have a lot of ERROR and WARNING log information. Every time I restart scrapydweb, the log reminder threshold is reached, resulting in a lot of emails being pushed to me. Is there any way to solve this problem?

**Comment by my8100** [comment]
> Some of my existing projects have a lot of ERROR and WARNING log information. Every time I restart scrapydweb, the log reminder threshold is reached, resulting in a lot of emails being pushed to me. Is there any way to solve this problem?

Are the new emails triggered by any new spider job?
