### ISSUE TITLE
Can't run scrapydweb when server use auth

### ISSUE THREAD

**Issue by Adam0407** [my8100/scrapydweb#77]
when i config username&password in server , scrapydweb cant run ,it shows 'None of your SCRAPYD_SERVERS could be connected.' 
but when i not use auth , scrapydweb can run,i have update my scrapydweb to match server auth configration by `pip install -U git+https://github.com/my8100/scrapydweb.git` ,it still the same

**Comment by my8100** [comment]
I pushed some update just now, please update your scrapydweb again and post the full log after it’s restarted.

**Comment by Adam0407** [comment]
man,i dont know why , i just restart my pc and scrapyweb worked,though i didn't do anything. the other weird thing is when i visit my server scrapyd through the original way (myserver:6800),it didn't show alert window for me to input username or password . and yes im sure i config the auth in scrapyd.

**Comment by my8100** [comment]
The basic auth is saved in the browser for a while, just use the requests library or curl command to verify it.

**Comment by my8100** [comment]
If you are using the git version of Scrapyd with basic auth enabled,
you can see the log “Basic authentication enabled” when it’s started.

**Comment by Adam0407** [comment]
thx man,i checked the curl command and the startup log of scrapyd on my server ,`Basic authentication enabled`, but scrapydweb still can't connect with my server(after i update the latest version by`pip install -U git+https://github.com/my8100/scrapydweb.git`),i think its authorization problem, cause console log shows 'status_code 401', here is the console log 

![image](https://user-images.githubusercontent.com/23303422/62406730-d3133b00-b5e2-11e9-94b1-51ebac592087.png)

**Comment by my8100** [comment]
You didn’t add the auth info in the SCRAPYD_SERVERS option!

**Comment by Adam0407** [comment]
my bad, didn't read comments carefully. thx a lot
